version: '3'

services:

  php-fpm:
    container_name: php-fpm
    build: .docker/php-fpm
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./.docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      - ./.docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - internal

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php-fpm
    networks:
      - internal

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28